services:
  rstudio:
    build:
      context: .
    environment:
      - DISABLE_AUTH=true
      - TZ=Asia/Tokyo
    volumes:
      - .:/home/rstudio/work
      - cache:/home/rstudio/.cache
      - venv:/home/rstudio/.venv
      - texlive:/home/rstudio/.texlive

volumes:
  cache:
    external: true
  venv:
    external: true
  texlive:
    external: true